name: chatops
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
  push:

jobs:
  default-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Handle common commands and run tests"
        uses: cloudposse/github-action-terraform-ci@f9fb382a1b33103e196e248d24f1d27eae9497b5
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
